### ISSUE TITLE
Typing indicator issues

### ISSUE THREAD

**Issue by Jolly-66** [Jolly-66/JollyStation#33]
first bug woot woot

but yeah, skrells seem to be exempt from the indicators?

**Comment by Jolly-66** [comment]
ok so it would appear some clients dont display/see their own indicators

**Comment by Jolly-66** [comment]
i'm going to assume this is a byond version issue and not inherently a code issue, hopefully

**Comment by MrMelbert** [comment]
the issue was people using the bottom bar to chat instead of the text box, btw. unfixable via our implementation
